version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bunk-mssql
    ports:
      - "1433:1433"
    volumes:
      - ./:/app
      - bunk-mssql-storage:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!"
    restart: always

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - mssql
    volumes:
      - ./:/app
    entrypoint: /bin/bash -c "
      echo 'Waiting for SQL Server to start...' && \
      sleep 30 && \
      echo 'Running SETUP.SQL...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/SETUP.SQL && \
      echo 'Running INSERT.SQL and saving outputInsert...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/INSERT.SQL -o /app/outputInsert.txt && \
      echo 'Running UPDATE.SQL...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/UPDATE.SQL && \
      echo 'Running FUNCTIONS.SQL...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/FUNCTIONS.SQL && \
      echo 'Waiting for objects to be available...' && \
      sleep 10 && \
      echo 'Running QUERY.SQL and saving output...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/QUERY.SQL -o /app/output.txt && \
      sleep 1 && \
      echo 'Running PROCEDURES.SQL and saving outputP...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/PROCEDURES.SQL -o /app/outputP.txt && \
      sleep 1 && \
      echo 'Running CUSOR.SQL and saving outputC...' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P 'StrongPass123!' -C -i /app/CUSOR.SQL -o /app/outputC.txt && \
      sleep 1 && \
      echo 'End'
      "

volumes:
  bunk-mssql-storage:
    name: bunk-mssql-storage
    driver: local
